spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/campus_help?serverTimezone=Asia/Shanghai
    username: gutian
    password: 123456

    druid:
      aop-patterns: com.yqn.*
      filters: stat,wall

      stat-view-servlet:
        enabled: true
        login-username: admin
        login-password: admin

      web-stat-filter:
        enabled: true
        url-pattern: /*

      mail:
        username: 2530141349@qq.com
        password: ghgpfsysstrrdiig
        host: smtp.qq.com
        protocol: smtp
        default-encoding: UTF-8
        properties:
          mail.smtp.auth: true
          mail.smtp.starttls.enable: true
          mail.smtp.starttls.required: true
          mail.smtp.socketFactory.port: 587 #协议为SMTP是SSL端口号465
          mail.smtp.socketFactory.class: javax.net.ssl.SSLSocketFactory
          mail.smtp.socketFactory.fallback: false

logging:
  level:
    com.yqn.mapper: debug
